before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: UJyrrLstNA22Q98B/0waam9b8e/YKLEhAE1LTDgOFJbR8O2blnxPfs5QQJe7nTKV6VyhZhkiacZLj/5uG+fQ4EHlkUotmbAiByXtFqxRc3tuHS+QgIFl7/Jh8rR5QWUCqIO6q+BzMWRNVboBCyrirxXZxKvlJCJ94V6wAx48iy1iwtkTUng/7BNZFGTkIPq0SbKKD03Do4GrnxdUs3yo7p87QAEmAPZkpykyywexoKROxCobUNMvcUuS/AfjXrElefeegr4Mj69bPBeNn3xSzSq9Eu3An7T/WQbx/fCX3EKX3nUWHrpR5njKmvs/QcfbXfUjyv7UyQubCkfyScVxVHF8Kosazb8DG1xCgJ/SVhZKJSVw5+jdytBm8FakP63YZ1VBl554ZaHCVhaB0tM6rG7qUT+92C5aZqJ1Aq2ni99W6Jt62q8E/UD0Yj88fjw1ofLXQXMPUyTvmjt5/RYf5KaT+9gb2mHHlGM9f0zBhdE2WyO+3bdgnjVBEZhEkfDioEqER2IsQc2gHKTZ6RMHytlJYuhsYL70xpa1N7xWJG2G42dVM6cygMBKNchS5gW9nUBMKAVX3X9JZJx6lnV6Rk22n+bsYEHATfQhJfOseefyKfTfpz63lB3+rFbDp9kf0rJntceqrtmwy8zxZJay5lTX8Yf1Pidfhs1IdLrdNa0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
